name: Create PR in web repo

on: 
    push: 
        branches-ignore:
            - main

env:
    ORG_SECRET: ${{ secrets.ORG_SECRET }}
    ORG_NAME: test-auto-pr-create

jobs:

   create_pr:
    runs-on: ubuntu-latest
    steps:
        # Step 1: Checkout the current repository (common-component)
        - name: Checkout common-component
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.ORG_SECRET }}

        # Step 2: Clone the target repository (web)
        - name: Clone web repository
          run: |
            git clone https://github.com/test-auto-pr-create/web.git
            cd web
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

        # Step 3: Copy changes from common-component to web
        - name: Copy changes to web repository
          run: |
            yarn install

        # Step 4: Push changes to a new branch in the web repository
        - name: Push changes to web repository
          run: |
            cd web
            git push origin -u install-dependencies

        # Step 5: Create a Pull Request in the web repository
        - name: Create Pull Request in web
          env:
            GITHUB_TOKEN: ${{ secrets.ORG_SECRET }}
          run: |
            cd web
            gh pr create --base main --head install-dependencies --title "install dependecies" --body "This PR syncs visualizer version from common-component."
